/** @Author Kamal Nayan
 **/
object Versions {
    const val coreKtx = "1.12.0"
    const val material = "1.11.0"
    const val appcompat = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val lifecycleKtx = "2.6.2"
    const val lifecycleViewModelKtx = "2.5.1"
    const val fragmentKtx = "1.6.2"
    const val livedataKtx = "2.6.2"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.5"
    const val espresso = "3.5.1"
    const val hilt = "2.48"
    const val safeArgs = "2.5.1"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val loggingInterceptor = "4.8.1"
    const val sandwich = "1.2.4"
    const val coroutine = "1.8.0-RC2"
    const val glide = "4.13.2"
    const val epoxy = "5.1.1"
    const val kotlinStdLib = "1.9.10"
    const val navigationFragmentKtx = "2.5.3"
    const val navigationUiKtx = "2.5.3"
    const val shimmer = "0.5.0"
    const val room = "2.5.2"
    const val paging = "3.2.1"
}